blank_issues_enabled: false
contact_links:
  - name: âš  Feature request
    url: https://github.com/Tyrrrz/YoutubeExplode.Converter/wiki/Maintenance-mode
    about: Sorry, but this project is in maintenance mode and no longer accepts new feature requests.
  - name: ðŸ’¬ Discord server
    url: https://discord.gg/2SUWKFnHSm
    about: Chat with the project community.
  - name: ðŸ—¨ Discussions
    url: https://github.com/Tyrrrz/YoutubeExplode.Converter/discussions/new
    about: Ask and answer questions.
  - name: ðŸ”— YoutubeExplode Issues
    url: https://github.com/Tyrrrz/YoutubeExplode/issues
    about: File issues related to YoutubeExplode in its dedicated repository.